### ISSUE TITLE
content-length KeyError

### ISSUE THREAD

**Issue by Bob131** [Boltovnya/8changrab#23]
```
[01:32:08] <fapper> spam incoming
[01:32:21] <fapper> Traceback (most recent call last):
[01:32:24] <fapper>   File "dl.py", line 153, in <module>
[01:32:26] <fapper>     sys.exit(main(sys.argv))
[01:32:28] <fapper>   File "dl.py", line 141, in main
[01:32:30] <fapper>     results = p.get(0xFFFF)
[01:32:32] <fapper>   File "/usr/lib/python3.2/multiprocessing/pool.py", line 559, in get
[01:32:33] <fapper>     raise self._value
[01:32:36] <fapper> KeyError: 'content-length'
[01:32:37] <fapper> thats all
```

Working on a fix :)

**Comment by Bob131** [comment]
Pardon, this is the same as #15 but the traceback comes from #20
