### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by smalltock** [Boltovnya/8changrab#26]
The program works just fine, it's just that after everything is downloaded, I'm getting a crash. Take this paste, for example:

    Traceback (most recent call last):=======>] 6/6 [100%]
      File "/home/smalltock/bin/infinity.py", line 153, in <module>
        main()
      File "/home/smalltock/bin/infinity.py", line 126, in main
        grabber.image_urls()
      File "/home/smalltock/bin/infinity.py", line 109, in image_urls
        pool_map.get(0xFFFF)
      File "/usr/lib64/python3.4/multiprocessing/pool.py", line 599, in get
        raise self._value
      File "/usr/lib64/python3.4/multiprocessing/pool.py", line 383, in _handle_tasks
        put(task)
      File "/usr/lib64/python3.4/multiprocessing/connection.py", line 206, in send
        self._send_bytes(ForkingPickler.dumps(obj))
      File "/usr/lib64/python3.4/multiprocessing/reduction.py", line 50, in dumps
        cls(buf, protocol).dump(obj)
      File "/usr/lib64/python3.4/multiprocessing/sharedctypes.py", line 192, in __reduce__
        assert_spawning(self)
      File "/usr/lib64/python3.4/multiprocessing/context.py", line 347, in assert_spawning
        ' through inheritance' % type(obj).__name__
    RuntimeError: Synchronized objects should only be shared between processes through inheritance

 

I'm not a big python guy and I'm not so sure what I'm doing, but I found that the problem just went away when I replaced lines 108-116 with the following two simple statements:

    pool.close()
    pool.join()

**Comment by Gosha** [comment]
Bottom of message in commit https://github.com/Boltovnya/8changrab/commit/3309de131d14f624efab5e5f1850be1728dac2c2 explains why `pool_map.get(0xFFFF)` is there in the first place

**Comment by smalltock** [comment]
Oh, okay, so it's just for the Ctrl-C case. Well something's up with the stacktrace, either way. I'm not python enough to figure it out.
